### ISSUE TITLE
Update Post Model

### ISSUE THREAD

**Issue by rohitkrishna094** [KristianWEB/fakebooker-backend#20]
**Is your feature request related to a problem? Please describe.**
Update Post.js in models folder. We will need to create the below model and export it as mongoose model from this file.

```js
{
    source: String, // ObjectId of person who made the post
    destination: String, // ObjectId of person who received the post(whose wall?)
    typeOfPost: String, // Type of post[i.e., text, image, url like reddit?]
    content: String, // actual content of the post
    creationDate: Number, // unix timestamp of when this post was created
    likedBy: [{
        id: String, // ObjectId of the user,
    }], // array of users who liked this post
    disLikedBy: [{
        id: String, // ObjectId of the user,
    }], // array of users who disliked this post
    edited: boolean,
    lastEditedDate: Number, // unix timestamp lastEdited
    comments: [Comment], // array of comments
}
```

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by williamj1788** [comment]
If Post is still going to be its own collection then you don't have to define an id property for the model. MongoDB automatically does that for you. Also, mongoose has an ObjectId type we could use instead of "string". Less error-prone and a little more descriptive.

**Comment by rohitkrishna094** [comment]
yeah updated it
